<?php
/**
 * @file
 * Create the Honor Role.
 */


/**
 * Implements hook_block_info().
 *
 * @return associative array
 */
function honor_roll_block_info()
{
    $blocks['honor_roll'] = array(
        'info' => t('Honor Roll'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
        'region' => 'Content',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => 'node/*'
    );
    return $blocks;
}

/**
 * Implements hook_admin().
 *
 * Creates the text input field for the settings page. Specifically the
 * area where the file path to the CSV file which contains the honor roll
 * data. This file will be read once a day and its contents will be cached.
 * 
 * @return array Settings form elements.
 */
function honor_roll_admin()
{
    $form = array();
    $currentPath = getcwd();
    $form['honor_roll_csv_file_path'] = array(
        '#type' => 'textfield',
        '#title' => t('CSV File Path'),
        '#default_value' => variable_get('honor_roll_csv_file_path'),
        '#size' => 50,
        '#maxlength' => 200,
        '#description' => "The file path to the CSV file containing the honor roll data.<br>This file is read once a day and the contents cached.<br><br>"."Current directory: ".$currentPath,
        '#required' => true,
    );
    return system_settings_form($form);
}

/**
 * Implements hook_menu()
 * 
 * @return array
 */
function honor_roll_menu()
{
    $items = array();
    $items['admin/settings/honor_roll'] = array(
        'title' => 'Honor Roll Module Settings',
        'description' => 'Honor Roll CSV file path.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('honor_roll_admin'),
        'access arguments' => array('administer honor roll settings'),
        'type' => MENU_SUGGESTED_ITEM,
    );
    return $items;
}

/**
 * Implements hook_block_view().
 *
 * @return array    Contents and Subject.
 */
function honor_roll_block_view($delta = '')
{
    switch ($delta) {
        case 'honor_roll':
            $block['subject'] = t('Get Today&#8217;s Weather');
            if (true == user_is_logged_in()) {
                $block['content'] = honor_roll_contents();
            } else {
                $block['content'] = 'You must be logged in to view weather.';
            }
    }
    return $block;
}

/**
 * Build the honor roll element structure.
 *
 * @return html
 */
function honor_roll_contents()
{
    $content = "Content will go here";
    return $content;
}
